### ISSUE TITLE
python3 compatibility 

### ISSUE THREAD

**Issue by rouxrei** [cloudera/cm_api#71]
I installed cm-api for python3 using pip without issues

    pip install cm-api

However, following the example on the [website](https://cloudera.github.io/cm_api/docs/python-client/) , I immediately get an error:
```
>>> from cm_api.api_client import ApiResource
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python\lib\site-packages\cm_api\api_client.py", line 23, in <module>
    from cm_api.http_client import HttpClient, RestException
  File "C:\Program Files\Python\lib\site-packages\cm_api\http_client.py", line 182
    except urllib2.HTTPError, ex:
                            ^
SyntaxError: invalid syntax
```
The error is obvious, python3 does not allow ','(comma) as syntax to declare an alias of an exception. 

It seems cm-api is NOT compatible with python3 since this commit: dcc11dfcddc0d565084f19e90d4fe62a39b9fe73
I could not find a reason for reverting the compatibility.

So either this lib should be removed from the pip3 repositories or this commit should be 'unreverted'?

**Comment by vojtechspacir** [comment]
Still a problem more than year after initial report.

Did anyone find a workaround other that using Ansible controller executable running on Python2.7?
