### ISSUE TITLE
It is failing to install the latest cm-api(version 20.0.0) with pip 

### ISSUE THREAD

**Issue by ggao** [cloudera/cm_api#73]
the following errors are showing to stop the installation while I run **pip install cm-api**: 
Collecting cm-api
  Using cached https://files.pythonhosted.org/packages/ae/e3/c79c1c36309af73c77cd61157baa547a1d24edb5ca761a40909480785cd9/cm_api-20.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/y1/kk6g44757wj5z327cctdl1hh0000gq/T/pip-install-v_gSi_/cm-api/setup.py", line 31, in <module>
        fobj = open(setup)
    IOError: [Errno 2] No such file or directory: '/private/var/folders/y1/kk6g44757wj5z327cctdl1hh0000gq/T/pip-install-v_gSi_/cm-api/python/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/y1/kk6g44757wj5z327cctdl1hh0000gq/T/pip-install-v_gSi_/cm-api/

**Comment by XavierTalpe** [comment]
Can confirm we have the same issue:

````
Collecting cm_api>=11.0.0 (from lilyfab->-r ngec2-fabprov-requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/ae/e3/c79c1c36309af73c77cd61157baa547a1d24edb5ca761a40909480785cd9/cm_api-20.0.0.tar.gz (65kB)
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/media/ephemeral1/tmp/pip-install-i6Sdsz/cm-api/setup.py", line 31, in <module>
    fobj = open(setup)
    IOError: [Errno 2] No such file or directory: '/media/ephemeral1/tmp/pip-install-i6Sdsz/cm-api/python/setup.py'
````

**Comment by mikhels** [comment]
Same here. OS: CentOS 6/7.

**Comment by mdwilco** [comment]
It's expecting setup.py to be in <tarball_root>/python and it’s actually just in the tarball root.  Installing the old version using cm-api==19.0.0 works.
