### ISSUE TITLE
cm_api.api_client.ApiException:  (error 404)

### ISSUE THREAD

**Issue by lihuimintu** [cloudera/cm_api#75]
Traceback (most recent call last):
  File "hdfs.py", line 37, in <module>
    Test()
  File "hdfs.py", line 29, in Test
    result = api.query_timeseries(query, from_time, to_time)
  File "/usr/lib/python2.6/site-packages/cm_api/api_client.py", line 295, in query_timeseries
    return timeseries.query_timeseries(self, query, from_time, to_time, by_post=by_post)
  File "/usr/lib/python2.6/site-packages/cm_api/endpoints/timeseries.py", line 75, in query_timeseries
    ApiTimeSeriesResponse, True, params=params, data=data)
  File "/usr/lib/python2.6/site-packages/cm_api/endpoints/types.py", line 139, in call
    ret = method(path, params=params)
  File "/usr/lib/python2.6/site-packages/cm_api/resource.py", line 110, in get
    return self.invoke("GET", relpath, params)
  File "/usr/lib/python2.6/site-packages/cm_api/resource.py", line 73, in invoke
    headers=headers)
  File "/usr/lib/python2.6/site-packages/cm_api/http_client.py", line 183, in execute
    raise self._exc_class(ex)
cm_api.api_client.ApiException:  (error 404)

**Comment by lihuimintu** [comment]
api版本造成的问题，可以阅读一下该链接
https://community.cloudera.com/t5/Cloudera-Manager-Installation/CM-Python-API/td-p/60338
